---
- name: Install i3wm
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
     - "@X Window System" 
     - "@Desktop" 
     - "@Desktop Platform" 
     - lightdm                  
     - xorg-x11-xinit-session 
     - i3
     - i3status 
     - i3lock 
     - cabextract
     - xorg-x11-font-utils 
     - fontconfig
     - https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
