---
 - import_tasks: tasks/install_oc.yml
   become: yes
   become_user: root
   tags:
     - install_oc
 
 - import_tasks: tasks/install_minishift.yml
   become: yes
   become_user: root
   tags:
     - install_minishift
 
 - import_tasks: tasks/grant_admin.yml
   become: yes
   become_user: root
   tags:
     - grant_admin
 
