---
- name: KVM Install
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
   - qemu-kvm 
   - libvirt 
   - virt-install 
   - bridge-utils 
   - bind-utils
   - virt-manager 
   - net-tools 
   - virt-viewer 
   - genisoimage 
