---
 # Enable Libvirtd 
 - name: enable service httpd and ensure it is not masked
   systemd:
     name: libvirtd
     enabled: yes
     masked: no

 # Starts Libvirtd
 - name: Make sure a service is running
   systemd: state=started name=libvirtd

 # Reloads Systemd
 - name: just force systemd to reread configs (2.4 and above)
   systemd: daemon_reload=yes
