---
- name: (RedHat) install ELRepo key
  become: yes
  become_user: root
  rpm_key: state=present key='https://www.elrepo.org/RPM-GPG-KEY-elrepo.org'

- name: (RedHat) get rpm...
  become: yes
  become_user: root
  get_url: >-
    url=http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    dest=/tmp/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    owner=root
    group=root
    mode=0644
    timeout=30
  
- name: (RedHat) install ELRepo
  become: yes
  become_user: root
  package: state=present name=/tmp/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
