---
- name: Copy the EPEL repository definition
  become: yes
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  become: yes
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

- name: Install Elrepo Key
  become: yes
  become_user: root
  rpm_key: state=present key='https://www.elrepo.org/RPM-GPG-KEY-elrepo.org'

- name: Download RPM ElRepo
  become: yes
  become_user: root
  get_url: >-
    url=http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    dest=/tmp/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    owner=root
    group=root
    mode=0644
    timeout=30
  
- name: Install ELRepo
  become: yes
  become_user: root
  package: state=present name=/tmp/elrepo-release-7.0-3.el7.elrepo.noarch.rpm

- name: install the nux-desktop repo
  become: yes
  yum:
    name: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
    state: present

